services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: shrinkitpy_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shrinkitpy_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/shrinkitpy_dev
      - FLASK_ENV=development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: sh -c "python migrate.py migrate && python app.py"

volumes:
  postgres_data:
